version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: royberT0908*
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    